name: Check PR

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']
        types: [opened, synchronize]

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v3
              with:
                  version: latest-8
                  run_install: true

            - name: Lint
              run: pnpm run lint

            - name: Check types
              run: pnpm run check-types

    test:
        name: Test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v3
              with:
                  version: latest-8
                  run_install: true

            - name: Test
              run: pnpm run test

    storybook:
        name: Storybook
        timeout-minutes: 15
        runs-on: ubuntu-latest
        needs: [lint, test]
        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v3
              with:
                  version: latest-8
                  run_install: true

            - name: Storybook
              run: pnpm run build-storybook

    build:
        name: Build
        timeout-minutes: 15
        runs-on: ubuntu-latest
        needs: [lint, test]
        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v3
              with:
                  version: latest-8
                  run_install: true

            - name: Build
              run: pnpm run build
